# Generated by Django 4.1.3 on 2022-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_video",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
